name: test
on:
  workflow_dispatch:
    inputs:
      images:
        type: string
        description: enter your image
        required: true
jobs:
  job1:
    name: job one
    runs-on: ubuntu-latest
      steps:
        - name: make file
          run: echo ${{ inputs.images }} > ${{ inputs.images }}.txt
        - name: uploade file
          uses: actions/upload-artifact@v4
          with:
            name: data
            path: ${{ inputs.images }}.txt
          run: echo OK!
