name: Start
on:
    workflow_dispatch:
        inputs:
            name:
                description: enteryouname
                type: string
                required: true
                

jobs:
    my-job:
      name: My Job
      runs-on: ubuntu-latest
      steps:
      - name: show ll
        run: echo ${{ inputs.name }}
     - name: Setup Debug Session
       uses: csexton/debugger-action@master

