name: Start
on:
    workflow_dispatch:|
        run

jobs:
    my-job:
      name: My Job
      runs-on: ubuntu-latest
      steps:
      - name: show ll
        run: ls -a -l
      - name: mkdir
        run: |
          mkdir hello && 
          echo "md hello" &&
          cd hello &&
          echo cd hello &&
          mkdir data &&
          echo md data 
      - run:
        work
      - name: show ll
        run: ls -a -l
